### ISSUE TITLE
Multiple editors on one page

### ISSUE THREAD

**Issue by arsiliath** [y-crdt/yrb-actioncable#1]
Hi - thank you for sharing this code.

I have multiple editors on one page.

If   ``_proto.connectBc = function connectBc() `` runs, then they both end up broadcasting to each other, so they end up identical. But I want two separate ydocs with different contents.

I think that because it's only using the channel name inside that function, so it can't differentiate between different paths in the publish call.
 
Not sure - I don't really understand any of this. However, changing this fixed my issue.

**Comment by eliias** [comment]
@arsiliath thanks for reporting the issue. I probably would have run into this soonish as well, but I haven't actually used in production yet (and I wasn't aware anyone else uses it).

**Comment by jstoup111** [comment]
This issue isn't isolated to multiple editors. It affects different pages with different channels set. Browser broadcast in general is not isolating to the channel and params passed and instead accepting everything.

**Comment by eliias** [comment]
Hey folks, it is very much possible that this isn't working at all (Although I'd hope that channel isolation works, but the `main` branch is pretty far behind, so I can't rule it out).

Just to let you know, the work on this gem started when I was involved in real-time collaboration projects at GitLab, but as I am no longer working there, there is no sponsor for this work. I am slowly getting back into CRDT work, but it might take a while for me to finish what I started. If someone is willing to work on this, I am happy to give guidance and hop on a call.

**Comment by jstoup111** [comment]
I'll see what I can do in order to help out. I don't find this issue in particular to be a large problem since configuring cross-browser is easy enough to disable. From my perspective this seems more ideal as I think I saw duplicate messages going out with CB turned on. 

```
new WebsocketProvider(
      ydoc,
      actionCableConsumer,
      "room",
      { id: "room/foo" },
      { disableBc: true, awareness: new Awareness(ydoc) }
    )
```
