### ISSUE TITLE
When will v0.1.6 or patch version be released?

### ISSUE THREAD

**Issue by NerdyBoyCool** [y-crdt/yrb-actioncable#43]
@eliias 

First of all, thank you for the great gem.

We are trying to use this gem in a closed beta product. We will actually offer this functionality to our users on a trial basis, although the number of users using it is small.

So I have a request. I would like you to release a new version (0.1.6 or patch version) including the following commits Without this change, we will get errors in name resolution on CI.
https://github.com/y-crdt/yrb-actioncable/pull/41

**Comment by eliias** [comment]
@NerdyBoyCool Hey, I am back by Tuesday and can release it. A word of warning though, this gem is not ready for production at all.

**Comment by NerdyBoyCool** [comment]
@eliias 
Thank you!

> this gem is not ready for production at all.

I understood that 👍

**Comment by eliias** [comment]
@NerdyBoyCool 0.1.6 is available now https://rubygems.org/gems/y-rb_actioncable/versions/0.1.6

**Comment by NerdyBoyCool** [comment]
@eliias Thank you very much !!!!
