### ISSUE TITLE
How to get editor full text value?

### ISSUE THREAD

**Issue by NerdyBoyCool** [y-crdt/yrb-actioncable#49]
We are currently storing document data with Redis as the destination, using the EXAMPLE example as a guide.

Is there any way to extract only the input string information from the binary data exchanged by y.js?

I am planning to store the data in mysql as well as Redis, using batches and such. However, the data used in this library is binary information that follows the y.js protocol, so I would like to handle it in a simple markdown-like format.

Also, I'm assuming that when I return values from mysql to editor, I need to re-convert them to a form that follows the y.js protocol. If you know how to do that, please let me know.

**Comment by Horusiath** [comment]
> I would like to handle it in a simple markdown-like format.

@NerdyBoyCool what is the use case for that? Updates contains a ton of information that's compressed and not very efficient for the textual representation.

**Comment by eliias** [comment]
@NerdyBoyCool If you want to interact with the data on the server, please take a look at the `y-rb` documentation: https://y-crdt.github.io/yrb/Y/Text.html#to_s-instance_method

As @Horusiath already stated, you need to be careful. If you just want to “read” the current state of the text on the server, you can use `to_s` for `Text` or similar methods for the other available types.
